### ISSUE TITLE
Multiple selections using cmd + click not working anymore.

### ISSUE THREAD

**Issue by iainvdw** [facebooknuclide/hyperclick#20]
**Problem**
Since the latest update, the default `cmd + click` functionality to make multiple selections doesn't seem to work anymore. Found out by brute forcing some combinations that it's now `cmd + alt + click`, but would like this to be `cmd + click` as per Atom's default again.

**Reproduce**
Install Hyperclick package, and the key combanation doesn't work anymore.

**Workaround**
When I start Atom in safe mode using `atom --safe` or when I disable the Hyperclick package, it works again.

**Comment by hansonw** [comment]
By default Hyperclick overrides cmd+click, but this is easily configurable in Settings (Atom > Preferences > Packages > Hyperclick > Settings); just change it to something else.

<img width="433" alt="screen shot 2017-07-04 at 12 24 24 pm" src="https://user-images.githubusercontent.com/577378/27841143-bd49c9fa-60b3-11e7-872f-dd8b02fd92a1.png">

**Comment by iainvdw** [comment]
@hansonw I've uninstalled and reinstalled the package, but there is no settings screen to change this setting. Possibly related to other Hyperclick users with similar problems in #18 and #19?

Using latest versions, Atom 1.18.10 and Hyperclick 0.1.1. 

What seems strange is that in the search results, it shows up as a `facebooknuclide` package. But when viewing details or after installing, it shows the package belongs to `ocldbk`:

<img width="767" alt="hyperclick-package" src="https://user-images.githubusercontent.com/1300766/27842418-3b9f9752-610a-11e7-9cd4-0464b9bf7588.png">

**Comment by iainvdw** [comment]
Small update, when installing the `atom-ide-ui` package, which contains Hyperclick, it **does** show the Hyperclick trigger key settings (which solves the issue). Just not in the standalone Hyperclick package, which seems rather odd as it should install the exact same package right?

**Comment by hansonw** [comment]
Oh wow, that's just bizarre. I'm guessing there's some Atom package cache that's not being cleared? When you uninstall hyperclick, can you check that ~/.atom/packages/hyperclick is being deleted? Or maybe you had that symlinked previously?

"atom-ide-ui" actually bundles hyperclick inside it, so it's not quite installing the same thing. But if that's working you don't need to install hyperclick beside it :p

**Comment by iainvdw** [comment]
Found the issue! The package was actually deleted, but not from APM's cache (`~/.atom/.apm/`). After deleting that folder and restarting Atom, installing Hyperclick did reinstall successfully with the settings screen.

Seems like there's some weird caching issue going on?

**Comment by hansonw** [comment]
Nice! Glad you figured it out, I'll cross post your findings on the other issue.

**Comment by lukasnagl** [comment]
I just had the same issue when flow-ide installed hyperclick with an update (steelbrain/flow-ide/pull/90). Multi-selection stopped working, making me quite angry to be honest, and after I found out that hyperclick was responsible, I noticed that the settings did not show up in Atom.

A full reinstall of hyperclick and an Atom restart fixed it for me, causing the settings to show up: `apm uninstall hyperclick && apm install hyperclick`

I would strongly vote for a different default shortcut (at least speaking for Mac), in order to **not overwrite a core keyboard shortcut**.

Looking more closely at this package, I think it’s a great idea and has it’s place. Sadly, my first encounter with it was unpleasant because of this choice.
