### ISSUE TITLE
Feature request: click to open CSS preprocessor @imports

### ISSUE THREAD

**Issue by keithjgrant** [facebooknuclide/hyperclick#36]
I love Hyperclick when I’m working in JavaScript, but I also do a lot of the CSS work on our team, and I really wish I could use it there as well.

Sass, Less, and PostCSS support the use of `@import` to import partial stylesheets with the following syntax:

`@import "forms/controls";`

Where "forms/controls" is the relative path to the stylesheet partial. I would love to be able to Cmd-click on the `@import` statement to open up that partial.

**Comment by wbinnssmith** [comment]
Hi @keithjgrant! I agree this would be pretty cool.

The hyperclick package only really concerns itself with implementing the UI and interaction of hyperclicking -- leaving the action taken when clicked up to individual providers.

I'm going to close this since it's outside the scope of this package, but will post here if I discover a provider for css.

Hopefully some day someone can make an awesome provider for css and friends :)

**Comment by penx** [comment]
I've just started a plugin for this:

https://atom.io/packages/css-hyperclick
https://github.com/penx/css-hyperclick

@keithjgrant please give it a go and see if it works for you, I can make adjustments if not, or feel free to submit a PR/bug reports/feature requests.

@wbinnssmith this is my first Atom plugin, so if you have a few minutes to take a look at the code and make any suggestions, it would be appreciated!
