### ISSUE TITLE
Custom aliases or absolute paths

### ISSUE THREAD

**Issue by sfarthin** [facebooknuclide/hyperclick#45]
Is there a way to handle custom routes with tools such as `webpack alias`, `babel-plugin-root-import` or `import-resolver-babel-module`? Maybe looking at `moduleRoots` like described here: https://atom.io/packages/js-hyperclick ?

**Comment by pelmers** [comment]
I believe there isn't a way to do this in the hyperclick package itself since it is just an interface for surfacing providers' information. I suggest you add this functionality to the provider's side, like js-hyperclick has done.
Hyperclick doesn't have knowledge of what happens when a click is confirmed, for example opening files is completely provider implementation-dependent. https://github.com/facebook-atom/atom-ide-ui/blob/master/modules/atom-ide-ui/pkg/hyperclick/lib/types.js#L46-L48

**Comment by pelmers** [comment]
closing from inactivity, if you're still having an issue could you post at https://github.com/facebook-atom/atom-ide-ui instead?
